[functions.billing-webhook]
verify_jwt = false

[functions.pull-worldbank]
verify_jwt = true

[functions.pull-worldpop]
verify_jwt = true

[functions.calculate-vulnerability]
verify_jwt = true

[functions.cron-calculate-vulnerability]
verify_jwt = false
